name: CI

on: [push, workflow_dispatch]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat .version)"
          export branch=${{ github.ref_name }}
          echo ${branch//\\/_}
          chmod +x wibble2
          ./wibble2
        
      - name: Show workflow
        run: |
          echo GITHUB_WORKFLOW $GITHUB_WORKFLOW

      #- name: Apply Version Tag ${{ steps.get_version.outputs.version }}
      #  uses: tvdias/github-tagger@v0.0.1
      #  with:
      #    repo-token: ${{ secrets.GITHUB_TOKEN }}
      #    tag: ${{ steps.get_version.outputs.version }}

      - name: Create artifact
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: echo ${VERSION} > ci-${VERSION}

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-${{ steps.get_version.outputs.version }}
          path: ci-${{ steps.get_version.outputs.version }}
