on:
  workflow_run:
    workflows: ["Scan and Merge"]
    types:
      - completed

jobs:
  merge_pr:
    runs-on: ubuntu-latest
    steps:
      - name: merge PR
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: gh pr merge "$PR_URL" --rebase 
        env:
          PR_URL: ${{jobs.run-scan.outputs.pr_url}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
