name: Scan and Merge

outputs:
  pr_url:
    value: ${{ env.PR_URL }}

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: run scan
        run: echo "Scan ok"
        
