name: Scan and Merge

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: run scan
        run: echo "Scan ok for $PR_URL"
             echo "::set-output name=pr-url::$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
