name: wibble

on:
  push:
  workflow_dispatch:


jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: throw
        id: throw
        continue-on-error: true
        run: echo "::set-output name=message::This is a message"; exit 1
        
      - name: catch_ok
        if: ${{ steps.throw.conclusion == 'success' }}
        run: |
             echo ${{ steps.throw.outputs.message }}
 
      - name: catch_fail
        if: ${{ steps.throw.outcome == 'failure' }}
        run: |
             echo "FAIL"
             
  send:
    needs: message
    if: ${{ needs.scan.result == 'success' }}
    
    steps:
      - name: send_message
        run: echo "Message SUCCESS"
