name: wibble

on:
  push:
  workflow_dispatch:


jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: throw
        id: throw
        run: echo "::set-output name=message::This is a message"
        
      - name: catch_ok
        if: ${{ steps.throw.conclusion == 'success' }}
        run: |
             echo ${{ steps.throw.outputs.message }}
 
      - name: catch_fail
        if: ${{ steps.throw.conclusion == 'failure' }}
        run: |
             echo "FAIL"
