name: wibble

on:
  push:
  workflow_dispatch:


jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: throw
        id: throw
        run: echo "::set-output name=message::This is a message"; exit 1
        
      - name: catch_ok
        if: always() && ${{ steps.throw.conclusion == 'success' }}
        run: |
             echo ${{ steps.throw.outputs.message }}
 
      - name: catch_fail
        if: always() && ${{ steps.throw.conclusion == 'failure' }}
        run: |
             echo "FAIL"

      - name: status
        run: echo "status $${{ job.status }}"
        
      - name: trap_throw_status
        if: ${{ steps.throw.outcome == 'failure' }}
        run: exit 1

  send:
    runs-on: ubuntu-latest
    needs: message
    
    steps:
      - name: send_message
        run: echo "Message SUCCESS"
