name: wibble

on:
  push:
  workflow_dispatch:


jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: throw
        id: throw
        run: echo "::set-output name=message::This is a message"
        
      - name: catch
        run: |
             echo ${{ steps.throw.outputs.message }}
             printenv
